#!/bin/bash

if [ "$UID" -ne 0 ]; then
    sudo /usr/bin/4to6tunnelstop
    exit $?
fi

source /etc/4to6tunnel/conf.sh

ip addr del "$IP4TO6TUNNEL_IP4" dev ip4tunnel
ip link set dev 4to6tunnel down
ip -6 tunnel del 4to6tunnel

exit 0
